pom.xml
The newest version has a handful of cool features, such as the ability to detect wrongly-named loggers.
This is similar to https://github.com/dropwizard/dropwizard/pull/814.
=> Bump SLF4J API version

metrics-jvm/src/main/java/com/codahale/metrics/jvm/ThreadStatesGaugeSet.java
=> Fix generic integer return type

metrics-servlets/src/main/java/com/codahale/metrics/servlets/MetricsServlet.java, metrics-servlets/src/test/java/com/codahale/metrics/servlets/MetricsServletTest.java
Added request parameters ``type`` and ``key`` to ``/metrics``.
=> Added request parameters type and key to /metrics

metrics-healthchecks/src/main/java/com/codahale/metrics/health/HealthCheckRegistry.java
=> #783 - Report HealthCheck as unhealthy on exception

metrics-adapter/src/main/java/com/codahale/metrics/Timer.java, metrics-core/src/main/java/io/dropwizard/metrics/Timer.java, metrics-core/src/test/java/io/dropwizard/metrics/TimerTest.java
Small improvement that allows Timer.Context to be used in try-with-resources
=> Timer.Context now implements AutoCloseable

docs/source/manual/third-party.rst
Please add metrics-atsd module to your project as third party module.
=> add metrics-atsd perorter link

docs/source/manual/third-party.rst
Also:
* converted all entries to proper sentences.
* updated a few old links.
=> Organize third-party doc for better readability

docs/source/manual/log4j.rst, metrics-log4j2/pom.xml, metrics-log4j2/src/main/java/io/dropwizard/metrics/log4j2/InstrumentedAppender.java, metrics-log4j2/src/test/java/io/dropwizard/metrics/log4j2/InstrumentedAppenderConfigTest.java, metrics-log4j2/src/test/resources/log4j2-testconfig.xml
The same changeset as PR #900, ported to the metrics master branch.
=> Metrics 4.0 log4j2 xml configuration

metrics-servlets/pom.xml, metrics-servlets/src/main/java/com/codahale/metrics/servlets/AdminServlet.java, metrics-servlets/src/main/java/com/codahale/metrics/servlets/CpuProfileServlet.java, metrics-servlets/src/test/java/com/codahale/metrics/servlets/AdminServletTest.java, metrics-servlets/src/test/java/com/codahale/metrics/servlets/CpuProfileServletTest.java
=> Add CPU profiling support to the AdminServlet

metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteReporter.java
Reverts dropwizard/metrics#933
=> Revert "Support for publishing metrics of BigInteger and BigDecimal type"

metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteReporter.java
See also: https://github.com/dropwizard/metrics/pull/933
=> Support for publishing metrics of BigInteger and BigDecimal type

metrics-healthchecks/src/main/java/com/codahale/metrics/health/HealthCheck.java, metrics-healthchecks/src/test/java/com/codahale/metrics/health/HealthCheckTest.java, metrics-json/src/main/java/com/codahale/metrics/json/HealthCheckModule.java, metrics-json/src/test/java/com/codahale/metrics/json/HealthCheckModuleTest.java
New pull request on 3.2-development
=> METRICS-#663: add support for custom details in HealthCheck.Result

metrics-httpclient/src/main/java/io/dropwizard/metrics/httpclient/HttpClientMetricNameStrategies.java, metrics-httpclient/src/test/java/io/dropwizard/metrics/httpclient/HttpClientMetricNameStrategiesTest.java
Many thanks to @phearnot for this patch, slightly modified for v4.
=> Improve hostname extraction for wrapped HTTP requests (v4)

.travis.yml, metrics-jersey2/pom.xml, metrics-jetty9/pom.xml, pom.xml
=> Move to Java 8

metrics-core/src/main/java/io/dropwizard/metrics/SlidingWindowReservoir.java, metrics-core/src/main/java/io/dropwizard/metrics/UniformReservoir.java, metrics-core/src/main/java/io/dropwizard/metrics/UniformSnapshot.java, metrics-core/src/test/java/io/dropwizard/metrics/UniformSnapshotTest.java
Applies #972 to master, and adds an unsafe protected constructor for use by trusted code.
=> Optimize creation of UniformSnapshot

docs/source/about/contributors.rst, docs/source/manual/collectd.rst, docs/source/manual/index.rst, metrics-collectd/pom.xml, metrics-collectd/src/main/java/io/dropwizard/metrics/collectd/Collectd.java, metrics-collectd/src/main/java/io/dropwizard/metrics/collectd/CollectdReporter.java, metrics-collectd/src/main/java/io/dropwizard/metrics/collectd/DataType.java, metrics-collectd/src/main/java/io/dropwizard/metrics/collectd/Network.java, pom.xml
Essentially it is the same as graphite udp reporter but implements collectd protocol.
=> 870: collectd reporter

metrics-graphite/src/main/java/io/dropwizard/metrics/graphite/GraphiteReporter.java, metrics-graphite/src/test/java/io/dropwizard/metrics/graphite/GraphiteReporterTest.java
And log a warning if the value to be reported cannot be parsed.
=> Fall back to java.lang.Number for publishing values to graphite.

docs/source/manual/third-party.rst
Note that I only commited on branch 3.2-develoment, please tell me if I should report changes to master/4.0
=> Add Hawkular Metrics reporter

metrics-graphite/src/main/java/com/codahale/metrics/graphite/Graphite.java, metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteReporter.java, metrics-graphite/src/test/java/com/codahale/metrics/graphite/GraphiteReporterTest.java, metrics-graphite/src/test/java/com/codahale/metrics/graphite/GraphiteTest.java
Redux of #899, because the origin pull request has become outdated.
=> #814 Always close socket in Graphite client

metrics-jvm/src/main/java/io/dropwizard/metrics/jvm/ThreadDump.java, metrics-jvm/src/test/java/io/dropwizard/metrics/jvm/ThreadDumpTest.java
JStack puts thread name in quotes and IntelliJ Idea can parse (via Analyze Stacktrace) such format.
=> Thread name should be quoted (as jstack does)

metrics-core/src/main/java/com/codahale/metrics/ScheduledReporter.java
Backport of #1049 to the 3.1 branch.
=> Suppress all kinds of Exceptions raised by report() (#1049)

pom.xml
Should be the last one which is support by JDK6
=> Upgrade to Jackson 2.6.6

metrics-log4j2/pom.xml, metrics-log4j2/src/main/java/com/codahale/metrics/log4j2/InstrumentedAppender.java
This looks like the last version which supports Java 1.6
=> Upgrade log4j2 to 2.3

metrics-graphite/src/main/java/com/codahale/metrics/graphite/Graphite.java, metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteReporter.java, metrics-graphite/src/test/java/com/codahale/metrics/graphite/GraphiteReporterTest.java, metrics-graphite/src/test/java/com/codahale/metrics/graphite/GraphiteTest.java
Move 2762ce5 from the 3.1 branch to 3.2
=> #814 always close socket to 3.2 branch

metrics-core/src/main/java/com/codahale/metrics/SlidingTimeWindowReservoir.java, metrics-core/src/test/java/com/codahale/metrics/SlidingTimeWindowReservoirTest.java
Backport of #1063 to the 3.1 branch
=> Backport sliding time reservoir fix

metrics-core/src/main/java/com/codahale/metrics/CsvFileProvider.java, metrics-core/src/main/java/com/codahale/metrics/CsvReporter.java, metrics-core/src/main/java/com/codahale/metrics/FixedNameCsvFileProvider.java, metrics-core/src/main/java/com/codahale/metrics/JmxAttributeGauge.java, metrics-core/src/main/java/com/codahale/metrics/JmxReporter.java, metrics-core/src/main/java/com/codahale/metrics/SharedMetricRegistries.java, metrics-core/src/main/java/com/codahale/metrics/Slf4jReporter.java, metrics-core/src/test/java/com/codahale/metrics/CsvReporterTest.java, metrics-core/src/test/java/com/codahale/metrics/FixedNameCsvFileProviderTest.java, metrics-core/src/test/java/com/codahale/metrics/JmxAttributeGaugeTest.java, metrics-core/src/test/java/com/codahale/metrics/SharedMetricRegistriesTest.java, metrics-core/src/test/java/com/codahale/metrics/Slf4jReporterTest.java, metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteReporter.java, metrics-graphite/src/test/java/com/codahale/metrics/graphite/GraphiteReporterTest.java, metrics-healthchecks/src/main/java/com/codahale/metrics/health/HealthCheckRegistry.java, metrics-jvm/src/main/java/com/codahale/metrics/jvm/MemoryUsageGaugeSet.java, metrics-jvm/src/main/java/com/codahale/metrics/jvm/ThreadDump.java, metrics-jvm/src/test/java/com/codahale/metrics/jvm/MemoryUsageGaugeSetTest.java, metrics-jvm/src/test/java/com/codahale/metrics/jvm/ThreadDumpTest.java, metrics-servlet/src/main/java/com/codahale/metrics/servlet/AbstractInstrumentedFilter.java
This backports the changes that were submitted to the 4.0 branch, but don't require Java 8. So, I guess we could release them as part of the 3.2 release.
=> Backport from 4.0

metrics-core/src/main/java/io/dropwizard/metrics/DefaultObjectNameFactory.java, metrics-core/src/main/java/io/dropwizard/metrics/JmxReporter.java, metrics-core/src/main/java/io/dropwizard/metrics/ObjectNameFactory.java, metrics-core/src/test/java/io/dropwizard/metrics/DefaultObjectNameFactoryTest.java
change signature on ObjectNameFactory to throw a MalformedObjectNameException
closes #1065
=> ObjectNameFactory throws MalformedObjectNameException

metrics-core/src/main/java/com/codahale/metrics/JmxReporter.java, metrics-core/src/test/java/com/codahale/metrics/JmxReporterTest.java
=> Report the size of the snapshot via JMX

docs/source/getting-started.rst, metrics-annotation/pom.xml, metrics-benchmarks/pom.xml, metrics-collectd/pom.xml, metrics-core/pom.xml, metrics-ehcache/pom.xml, metrics-graphite/pom.xml, metrics-healthchecks/pom.xml, metrics-httpasyncclient/pom.xml, metrics-httpclient/pom.xml, metrics-influxdb/pom.xml, metrics-jdbi/pom.xml, metrics-jersey2/pom.xml, metrics-jetty9/pom.xml, metrics-json/pom.xml, metrics-jvm/pom.xml, metrics-log4j2/pom.xml, metrics-logback/pom.xml, metrics-servlet/pom.xml, metrics-servlets/pom.xml, pom.xml
change the groupId so there is no collision with 3.x artifacts.
If there is another groupId that is preferred let me know.  
fixes #1069
=> GroupId change

pom.xml
=> Upgrade error_prone_core to 2.0.18

docs/source/about/release-notes.rst
=> Add 3.2.2 release notes

metrics-core/src/main/java/com/codahale/metrics/ScheduledReporter.java
See https://github.com/dropwizard/metrics/pull/1049 for details
=> Suppress all kinds of Throwables raised by report()

metrics-core/src/main/java/io/dropwizard/metrics/CachedGauge.java, metrics-core/src/main/java/io/dropwizard/metrics/Histogram.java, metrics-core/src/main/java/io/dropwizard/metrics/MetricRegistry.java, metrics-core/src/main/java/io/dropwizard/metrics/UniformReservoir.java, metrics-core/src/test/java/io/dropwizard/metrics/UniformReservoirTest.java, metrics-core/src/test/java/io/dropwizard/metrics/UniformSnapshotTest.java, metrics-graphite/src/test/java/io/dropwizard/metrics/graphite/GraphiteReporterTest.java
Fixes various warnings reported by Eclipse.
=> Fix various warnings
