dropwizard/metrics

- docs/source/manual/third-party.rst
As suggested by ryantenney in https://github.com/dropwizard/metrics/pull/733,
We've pushed our metrics-instrumental project to maven central, and here's a PR regarding an update to the third-party documentation.
Thanks!
> Added a reference to the metrics-instrumental 3rd party lib.

- metrics-core/src/main/java/com/codahale/metrics/Slf4jReporter.java
- metrics-core/src/test/java/com/codahale/metrics/Slf4jReporterTest.java
Avoid overhead when logging is disabled for the specified reporting log level or marker.
> Simplify slf4j reporting when logging is disabled

- metrics-jvm/src/main/java/com/codahale/metrics/jvm/MemoryUsageGaugeSet.java
- metrics-jvm/src/test/java/com/codahale/metrics/jvm/MemoryUsageGaugeSetTest.java
For monitoring memory usage, the memory used gauge is not very suitable to put automated analysis on, because it can be varying wildly. A better choice for these situations would be the JMX metric of the memory that's still in use after the last garbage collection. This gives a more accurate indication of retained memory, without varying short lived object allocation.
This pull requests adds it as a gauge to the memory pool gauge set with postfix "used-after-gc".
The rest of the CollectionUsage methods (init, committed, max) are of no value, since they're basically identical to the normal MemoryUsage of the same pool,  and are therefore not included.
> Add CollectionUsage.getUsed() to MemoryPool gauges

- metrics-core/src/main/java/com/codahale/metrics/JmxReporter.java
Use same string instance for rateUnit across all instances that have the same TimeUnit.
Fixes https://github.com/dropwizard/metrics/issues/802
> Use same string instance for rateUnit across all instances

- metrics-core/src/main/java/com/codahale/metrics/Timer.java
- metrics-core/src/test/java/com/codahale/metrics/TimerTest.java
Makes it easier to use Timer with Java 8.
See issue #807
> Add Timer.time method that accepts Runnable.

- metrics-core/src/main/java/com/codahale/metrics/JmxAttributeGauge.java
- metrics-core/src/test/java/com/codahale/metrics/JmxAttributeGaugeTest.java
If the object name is a pattern, perform a query for matching object
names and return the value of the given attribute if the pattern yields
a unique match. If the match is ambiguous, return null to avoid
returning the value from a wrong match.
The object name of an MBean consists of a domain part and a list of
key/value pairs that together form a unique identifier. The values,
however, often depend on current configuration parameters (i.e. the
hostname). By using an object name pattern it is possible to avoid the
need of considering configuration parameters when passing the object
name to the JmxAttributeGauge.
> Add support for patterns in MBean object names

- metrics-core/src/main/java/com/codahale/metrics/SharedMetricRegistries.java
- metrics-core/src/test/java/com/codahale/metrics/SharedMetricRegistriesTest.java
In https://github.com/dropwizard/metrics/issues/334, it was mentioned that the default metric registry has disappeared. While it makes sense to disallow a "default" default registry to prevent having a dumping ground for all metrics, this unfortunately creates a bit more complexity for multilayered services. If there's a shared registry of metrics between them, for instance, each of the pieces that make up a service would need to be cognisant of this default registry's name, even if the name has no semantic meaning. 
In order to reduce complexity, we are aiming to expose a method to set a default registry name and allow consumers to call into SharedMetricRegistries to access this default registry. This enables a single orchestrator (such as a service container) to initialize the default …
> Opt-in default shared registry

- metrics-servlet/src/main/java/com/codahale/metrics/servlet/AbstractInstrumentedFilter.java
Proposition for issue #795.
The requests timer and the activeRequests counter now properly observe the entire processing time. Use meters separate from the response code meters for timeouts and errors since the code isn't representative (i.e. 200) for these situations.
> Add support for async servlet to metrics-servlet

- pom.xml
Is there any reason to still keep compatibility with Java 1.6? If not, it would be nice to be able to use all the neat Java 1.7 language features.
> Allow Java 1.7 source level

- metrics-influxdb/pom.xml
- metrics-influxdb/src/main/java/com/codehale/metrics/influxdb/InfluxDbHttpSender.java
- metrics-influxdb/src/main/java/com/codehale/metrics/influxdb/InfluxDbReporter.java
- metrics-influxdb/src/main/java/com/codehale/metrics/influxdb/InfluxDbSender.java
- metrics-influxdb/src/main/java/com/codehale/metrics/influxdb/data/InfluxDbPoint.java
- metrics-influxdb/src/main/java/com/codehale/metrics/influxdb/data/InfluxDbWriteObject.java
- metrics-influxdb/src/main/java/com/codehale/metrics/influxdb/utils/InfluxDbWriteObjectSerializer.java
- metrics-influxdb/src/test/java/com/codehale/metrics/influxdb/InfluxDbReporterTest.java
- metrics-influxdb/src/test/java/com/codehale/metrics/influxdb/utils/InfluxDbWriteObjectSerializerTest.java
- metrics-influxdb/src/test/java/sandbox/SendToLocalInfluxDB.java
- pom.xml
Adding metrics-influxdb module to enable writing application metrics to [influxdb] (https://influxdb.com/docs/v0.9/introduction/overview.html). 
The latest v0.9 influxdb release was announced recently and it will be great to have metrics report to influxdb as well, similar to graphite.
> Adding a module to write metrics to InfluxDb

- metrics-influxdb/pom.xml
- metrics-influxdb/src/main/java/com/codehale/metrics/influxdb/utils/InfluxDbWriteObjectSerializer.java
- metrics-influxdb/src/test/java/com/codehale/metrics/influxdb/utils/InfluxDbWriteObjectSerializerTest.java
Getting rid of org.codehaus.jackson dependency and using the same jackson dependencies as the metrics-json module.
> Updating jackson dependencies to match the project

- metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteReporter.java
- metrics-graphite/src/test/java/com/codahale/metrics/graphite/GraphiteReporterTest.java
This prevents an unexpected exception from killing the reporter thread
silently. Instead log the exception and close the connection gracefully.
We observed this problem a few times with hystrix (for instance, hystrix 1.4.7 implements its own metrics which have had various bugs - in one case we saw an ArrayOutOfBoundsException when calling #getValue on a gauage). It was difficult to debug as the reporter thread silently dies since the exception is unhandled. In general I think we should be careful to avoid killing the scheduler thread.
> Handle unexpected exceptions when reporting to graphite

- README.md
Make shield "Maven Central" usable link to last version on maven central repository
> Make shield "Maven Central" usable link

- metrics-jersey2/src/main/java/com/codahale/metrics/jersey2/InstrumentedResourceMethodApplicationListener.java
- metrics-jersey2/src/test/java/com/codahale/metrics/jersey2/SingletonMetricsJerseyTest.java
- metrics-jersey2/src/test/java/com/codahale/metrics/jersey2/resources/InstrumentedResource.java
- metrics-jersey2/src/test/java/com/codahale/metrics/jersey2/resources/InstrumentedSubResource.java
The version of metrics in Dropwizard 0.8.2 was not registering metrics for subresources that are registered with a subresource locator.  This was reported in this issue:
https://github.com/dropwizard/metrics/issues/825.  The proposed solution in the issue didn't seem to make any difference so I took a different approach.
I made the diff on top of the 3.1-maintenance branch, looks like it would be fairly straightforward to put onto master as well.
> Fix https://github.com/dropwizard/metrics/issues/825 - subresources

- pom.xml
Assertj was bumped to 3.1.0 on 59e7c4a3dc255e30d3ce925bf4ad80f4c1ef7636 which breaks the build on JDK7.
```
AssertJ 1.x requires Java 6 or higher (suitable for Android)
AssertJ 2.x requires Java 7 or higher (not suitable for Android due to Path assertions)
AssertJ 3.x requires Java 8 or higher (not suitable for Android due to Path assertions)
```
> Downgrade assertj to 2.1.0

- metrics-core/src/main/java/io/dropwizard/metrics/ScheduledReporter.java
I noticed this message on the console occasionally and figured it could do to have it under the logger control like the others. 
Setting it at warn since there is not much the user could really do about it.
> Executor did not terminate message to use logger

- metrics-influxdb/pom.xml
- metrics-influxdb/src/main/java/io/dropwizard/metrics/influxdb/InfluxDbHttpSender.java
- metrics-influxdb/src/test/java/sandbox/SendToLocalInfluxDB.java
- pom.xml
A drop-in replacement for the current url-based impl.
However I'd like to "structure" the configuration better, and take username, password parameters instead of an username:pw authstring. WDYT?
> Refactor influxdb reporter to use Apache HttpClient

- metrics-graphite/src/main/java/io/dropwizard/metrics/graphite/Graphite.java
Do retry DNS lookups, which are just done in the constructor of
InetSocketAddress.
Reason might be that in some environments DNS is very dynamic and thus a name
might be sometimes resolveable and sometimes not. The way this is currently
implemented the InetSocketAddress is always cached, which in itself caches the
return value of the last DNS lookup, even if that failed.
> Retry DNS lookups

- metrics-core/src/main/java/io/dropwizard/metrics/CsvFileProvider.java
- metrics-core/src/main/java/io/dropwizard/metrics/CsvReporter.java
- metrics-core/src/main/java/io/dropwizard/metrics/FixedNameCsvFileProvider.java
- metrics-core/src/test/java/io/dropwizard/metrics/CsvReporterTest.java
- metrics-core/src/test/java/io/dropwizard/metrics/FixedNameCsvFileProviderTest.java
This PR extracts the naming of the CSV file from the CSV reporter itself. This allows users to come up with their own naming strategy. 
Using this code as a base, I have implemented a naming strategy that uses the current date to generate a file per day and allows to keep x days of files. If interested I can also contribute this in a separate pull request.
NOTE: Something went wrong when I tried to [fix my username](https://help.github.com/articles/changing-author-info/) so I had to delete my fork and create a new fork. So https://github.com/dropwizard/metrics/pull/879 is no longer valid. Sorry about that.
> Allow a pluggable strategy for the name of the CSV files that the CsvReporter uses

- metrics-graphite/src/main/java/io/dropwizard/metrics/graphite/PickledGraphite.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1155 - “Collection.isEmpty() should be used to test for emptiness”. You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1155
Please let me know if you have any questions.
Ahmed
> Code quality fix - Collection.isEmpty() should be used to test for emptiness

- metrics-json/src/main/java/io/dropwizard/metrics/json/HealthCheckModule.java
- metrics-json/src/main/java/io/dropwizard/metrics/json/MetricsModule.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2057 - “Serializable classes should have a version id”. You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS2057
Please let me know if you have any questions.
Ahmed
> Code quality fix - Serializable classes should have a version id

- docs/source/manual/third-party.rst
Added a link to a reporter, which uses MongoDB as a storage engine.
> Added link to mongodb reporter

- docs/source/manual/log4j.rst
- metrics-log4j2/pom.xml
- metrics-log4j2/src/main/java/com/codahale/metrics/log4j2/InstrumentedAppender.java
- metrics-log4j2/src/test/java/com/codahale/metrics/log4j2/InstrumentedAppenderConfigTest.java
- metrics-log4j2/src/test/resources/log4j2-testconfig.xml
This allows the use of the log4j2 InstrumentedAppender without needing code-based config. ie:
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="INFO" name="log4j2-config" packages="com.codahale.metrics.log4j2">
<Appenders>
<MetricsAppender name="metrics" registryName="shared-metrics-registry"/>
</Appenders>
<Loggers>
<Root level="INFO">
<AppenderRef ref="metrics" />
</Root>
</Loggers>
</Configuration>
For the most part, this was simply a matter of adding the right log4j2 plugin hooks. 
However, I ended up adding a new constructor because the concept of the appender name and the metrics prefix were tightly coupled. This was an irritation because the appender name is used as the logger reference in the XML config.
Also, since the test I added was actually initializing a logging …
> Add log4j2 xml-based config support

- docs/source/manual/core.rst
Here's a thought on some minor tweaks to the documentation.
I couldn't find any references to SharedMetricsRegistries in the docs, and it seems like a natural thing to use in many cases.
I was also thinking of this in the context of Issue #890, and that it might be a good place to insert that mention about the thread-safe design goal.
I removed most of the bit about multiple registries in a JVM. It never made much sense to me since registry instances don't have names, except in the context of SharedMetricsRegistries.
> Update Metric Registries section of the docs

- metrics-jersey2/src/main/java/io/dropwizard/metrics/jersey2/InstrumentedResourceMethodApplicationListener.java
- metrics-jersey2/src/test/java/io/dropwizard/metrics/jersey2/SingletonMetricsExceptionMeteredPerClassJerseyTest.java
- metrics-jersey2/src/test/java/io/dropwizard/metrics/jersey2/SingletonMetricsMeteredPerClassJerseyTest.java
- metrics-jersey2/src/test/java/io/dropwizard/metrics/jersey2/SingletonMetricsTimedPerClassJerseyTest.java
- metrics-jersey2/src/test/java/io/dropwizard/metrics/jersey2/resources/InstrumentedResourceExceptionMeteredPerClass.java
- metrics-jersey2/src/test/java/io/dropwizard/metrics/jersey2/resources/InstrumentedResourceMeteredPerClass.java
- metrics-jersey2/src/test/java/io/dropwizard/metrics/jersey2/resources/InstrumentedResourceTimedPerClass.java
- metrics-jersey2/src/test/java/io/dropwizard/metrics/jersey2/resources/InstrumentedSubResourceExceptionMeteredPerClass.java
- metrics-jersey2/src/test/java/io/dropwizard/metrics/jersey2/resources/InstrumentedSubResourceMeteredPerClass.java
- metrics-jersey2/src/test/java/io/dropwizard/metrics/jersey2/resources/InstrumentedSubResourceTimedPerClass.java
If a `Resource` class is annotated with either:
* `@Timed`,
* `@Metered`
* `@ExceptionMetered`
all method defined in such class will 'inherit' the corresponding annotation.
> Register metrics defined at Resource level

- docs/source/manual/third-party.rst
Just a link to a reporter which enables metrics collected by Dropwizard to be pushed into the Hadoop Metrics2 system.
> Adds a link to a third-party reporter for Hadoop Metrics2.

- metrics-core/src/main/java/io/dropwizard/metrics/FixedNameCsvFileProvider.java
- metrics-core/src/test/java/io/dropwizard/metrics/FixedNameCsvFileProviderTest.java
The current sanitization offered by the default CsvFileProvider does nothing.
Although this may be acceptable in most cases there are some known bad filename chars that we can restrict that cover
99% of the dropwizard user base (windows, unix, linux).
The forward slash '/' is illegal in all three OS and should be at a minimum sanitizied. The forward slash is a common
character in metric names if people are constructing metric names from URIs.
> Add basic sanitization for default CsvFileProvider

- metrics-jetty9/src/main/java/io/dropwizard/metrics/jetty9/InstrumentedConnectionFactory.java
Jetty 9.3.0 is the latest update of Jetty with some API changes.
* Update `InstrumentedConnectionFactory` to support instrumentation for Jetty 9.3. 
The update should be backward-compatible with Jetty 9.1 and 9.2, because we only implement a new method.
> Update for Jetty 9.3.0

- metrics-graphite/src/main/java/io/dropwizard/metrics/graphite/GraphiteRabbitMQ.java
- metrics-graphite/src/main/java/io/dropwizard/metrics/graphite/GraphiteSanitize.java
- metrics-graphite/src/main/java/io/dropwizard/metrics/graphite/GraphiteUDP.java
- metrics-graphite/src/main/java/io/dropwizard/metrics/graphite/PickledGraphite.java
- metrics-graphite/src/test/java/io/dropwizard/metrics/graphite/GraphiteSanitizeTest.java
Fix for #637, that supersedes #731 
The fix won't allow any characters that will interfere with Graphite's display or functions.
Instead of using fancy regex, this PR uses code ported from Guava's CharMatcher and Apache's StringUtils.
This PR was made against master because this may break other's graphite metric names, even if some of them aren't 100% valid (eg. `foo:bar` will be logged fine, but some graphite functions will break). Any potential breakage should be able to be fixed through [whisper-merge](https://github.com/graphite-project/whisper/blob/master/bin/whisper-merge.py). If this is wanted for 3.2.0, I'd be more than happy to send another PR against that.
> Graphite: Replace names with non-alphanumeric chars with '-'

- metrics-graphite/src/main/java/io/dropwizard/metrics/graphite/GraphiteReporter.java
- metrics-graphite/src/test/java/io/dropwizard/metrics/graphite/GraphiteReporterTest.java
When exporting metrics from hystrix to graphite (https://github.com/Netflix/Hystrix using  https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-codahale-metrics-publisher) we've seen that there are some interesting properties  like isCircuitBreakerOpen that are not exported to Graphite.
These properties are boolean values. We think it'd make sense to export them as 0/1 so they can be graphed alongside some other values.
> Export boolean values to graphite as 1/0

- docs/source/manual/third-party.rst
Turns out I hadn't added all the libraries I maintain.
(Also it looks like the doc site isn't up to date with the 3.1 branch, as the live page doesn't have the entry for metrics-munin-reporter.)
> Add links to more third party libs

- metrics-httpclient/src/main/java/com/codahale/metrics/httpclient/HttpClientMetricNameStrategies.java
- metrics-httpclient/src/test/java/com/codahale/metrics/httpclient/HttpClientMetricNameStrategiesTest.java
When executing a request, HttpClient will wrap the original request in HttpRequestWrapper so that e.g. redirects can be handled with ease. In such cases, the wrapper request has its URI rewritten (see org.apache.http.impl.execchain.ProtocolExec#rewriteRequestUri): the host part is stripped, so the wrapper's RequestLine can no longer be used to reliably obtain the hostname.
This pull request improves HOST_AND_METHOD and QUERYLESS_URL_AND_METHOD metric naming strategies by checking if the request is actually a wrapper and trying to obtain URI from the original request.
> Improve hostname extraction for wrapped HTTP requests

- metrics-core/src/main/java/com/codahale/metrics/UniformReservoir.java
- metrics-core/src/main/java/com/codahale/metrics/UniformSnapshot.java
- metrics-core/src/test/java/com/codahale/metrics/UniformSnapshotTest.java
Optimize creation of ``UniformSnapshot`` with less copies and boxing to ``Long`` and ``long``.
I kept the copy of the array itself when passed into the constructor to satisfy exposing a mutable array into the object, as per the findbugs warning.  Personally, I would like to remove that also since this is all internal to the library, but I understand why it is there.
Also, see comment in #970 about the removed tests.
> #970: optimize creation of UniformSnapshot

- metrics-core/src/main/java/io/dropwizard/metrics/CachedGauge.java
- metrics-core/src/main/java/io/dropwizard/metrics/Clock.java
- metrics-core/src/main/java/io/dropwizard/metrics/Counter.java
- metrics-core/src/main/java/io/dropwizard/metrics/Histogram.java
- metrics-core/src/main/java/io/dropwizard/metrics/Meter.java
- metrics-core/src/main/java/io/dropwizard/metrics/Timer.java
Keeping the basic output for Counter and Clock in the same line as the existing RatioGauge::toString, but for Histogram etc. tries a human friendly yet parseable output. Happy to amend to better formats anyway.
Fixes #566
> Override toString in Metric implementations

- docs/source/manual/graphite.rst
`Graphite` and `PickledGraphite` are both subclasses of `GraphiteSender`, so the edited line in docs does not compile.
> Minor fix in docs, using PickledGraphite instead of Graphite

- metrics-core/src/main/java/com/codahale/metrics/ExponentiallyDecayingReservoir.java
- metrics-core/src/test/java/com/codahale/metrics/ExponentiallyDecayingReservoirTest.java
Fixes issues #1005 and #793 - note that in #793 the `longPeriodsOfInactivityShouldNotCorruptSamplingState` test did not cover multiple concurrent requests after a long idle period.
The race condition currently occurs when two threads update the reservoir concurrently - after the first thread has successfully updated `nextScaleTime` (line 162) but before the write lock is obtained (line 163) a second thread updates the reservoir (line 95+).  With several threads pushing updates concurrently this presents a narrow window during which the second thread may obtain the lock before the first resulting in a corrupt reservoir state.  Note, however, that if a snapshot is requested just prior to the two concurrent updates the read lock will already be active when the two threads enter …
> Fix race condition in ExponentiallyDecayingReservoir's rescale method

- pom.xml
I've been having problems hooking up Dropwizard Metrics with [Finagle Metrics](https://github.com/rlazoti/finagle-metrics) and [Finatra](https://github.com/twitter/finatra) because of conflicting Jackson versions.
I've bumped the version of Jackson to the latest from Maven Central (2.8.5) and the tests all appear to pass successfully.
Are there any other areas that need looking at to ensure the upgrade doesn't break anything?
It may be worth considering this issue as well: https://github.com/dropwizard/metrics/issues/642
> Update Jackson to 2.8.5

- metrics-jcache/pom.xml
- metrics-jcache/src/main/java/com/codahale/metrics/jcache/JCacheGaugeSet.java
- metrics-jcache/src/test/java/JCacheGaugeSetTest.java
- metrics-jcache/src/test/resources/ehcache.xml
- pom.xml
This is a JCache module for metrics. It should works with any JCache compatible cache and was tested with Ehcache inside JHipster.
It was implemented by @anthonydahanne and I from Terracotta
> Add metrics jcache

- metrics-core/src/test/java/com/codahale/metrics/CounterTest.java
Sometimes developers pass variables without checking them .. so it could happen that they pass negative values to the inc method and positive values to the dec methods .. and thats why I added more unit tests to cover these 2 corner cases to the CounterTest class.
> Adding more unit tests for the Counter class to cover corner cases

- metrics-core/src/main/java/com/codahale/metrics/Timer.java
- metrics-core/src/test/java/com/codahale/metrics/TimerTest.java
This allows you to invoke method handles or lambdas that
don't return a value easily.
> Add an overload of Timer#time that takes Runnable

- metrics-core/src/test/java/com/codahale/metrics/CsvReporterTest.java
- metrics-core/src/test/java/com/codahale/metrics/DerivativeGaugeTest.java
- metrics-core/src/test/java/com/codahale/metrics/InstrumentedExecutorServiceTest.java
- metrics-core/src/test/java/com/codahale/metrics/InstrumentedScheduledExecutorServiceTest.java
I'm trying to contribute to this repo and I have already used it at work to monitor our backend application .. so I've decided to start looking at the unit tests to understand more about how the whole lib work and found some optimizations that could be added to some of the unit tests
> Optimizing unit tests

- metrics-jetty9-legacy/src/main/java/com/codahale/metrics/jetty9/InstrumentedConnectionFactory.java
This method is declared in `ConnectionFactory` in Jetty 9.3.*.
To be compatible with it, we should have a method with the same
signature.
We can't use a compile-time dependency on Jetty 9.3.*, because
it's compiled against Java 8, but `codahale-metrics` against Java 6.
Therefore, we use reflection to access this method.
Backport of #823
> Add `getProtocols` method

- metrics-jetty9-legacy/src/main/java/com/codahale/metrics/jetty9/InstrumentedConnectionFactory.java
- metrics-jetty9/src/main/java/com/codahale/metrics/jetty9/InstrumentedConnectionFactory.java
This method is declared in ConnectionFactory in Jetty 9.3.*.
To be compatible with it, we should have a method with the same
signature.
We can't use a compile-time dependency on Jetty 9.3.*, because
it's compiled against Java 8, but codahale-metrics against Java 6.
Therefore, we use reflection to access this method.
Backport of #823
> Fix "Add `getProtocols` method"

- metrics-httpclient/src/main/java/io/dropwizard/metrics/httpclient/HttpClientMetricNameStrategy.java
- metrics-httpclient/src/main/java/io/dropwizard/metrics/httpclient/InstrumentedHttpRequestExecutor.java
- metrics-httpclient/src/test/java/io/dropwizard/metrics/httpclient/InstrumentedHttpClientsTest.java
Adds counters for exceptions that happen after `InstrumentedHttpRequestExecutor.execute` has been invoked (some errors, like connection refused, invalid URLs, etc. don't make it that far). By default, use the simple name of the exception as the name of the meter, yielding names like     `org.apache.http.client.HttpClient.foobar.SocketTimeoutException`.
> Meters for httpclient exceptions

- metrics-jetty9/src/main/java/com/codahale/metrics/jetty9/InstrumentedQueuedThreadPool.java
Hello,
I want to add ability to set custom prefix in InstrumentedQueuedThreadPool in metrics-jetty9. In similar way to InstrumentedHandler.
I've added setter because I think there should be a simple way to set the prefix when someone wants to use existing defaults. Another way would be adding some additional constructors (obviously I don't want to break the existing api) - but that would bring some other design issues.
I'm not sure what's better - what do you think about it?
> Allow setting custom prefix in InstrumentedQueuedThreadPool

- metrics-jetty9/src/main/java/io/dropwizard/metrics/jetty9/InstrumentedConnectionFactory.java
- metrics-servlets/pom.xml
- metrics-servlets/src/test/java/io/dropwizard/metrics/servlets/AdminServletTest.java
- metrics-servlets/src/test/java/io/dropwizard/metrics/servlets/PingServletTest.java
- pom.xml
This update removes reflection hacks for supporting Jetty 9.3 and higher and allows to test the Jetty and Servlets modules against the latest Jetty version 9.4.0.v20161208. Metrics 4.0.0 supports Java 8, so the change is pretty straightforward.
> Upgrade Jetty integration to Jetty 9.4

- metrics-core/src/main/java/com/codahale/metrics/ScheduledReporter.java
- metrics-core/src/test/java/com/codahale/metrics/ScheduledReporterTest.java
- metrics-servlets/src/main/java/com/codahale/metrics/servlets/MetricsServlet.java
`ScheduledReporter.start()` incorrectly uses the interval size for the start delay, too:
```
public void start(long period, TimeUnit unit) {
executor.scheduleAtFixedRate(new Runnable() {
@Override
public void run() {
try {
report();
} catch (RuntimeException ex) {
LOG.error("RuntimeException thrown from {}#report. Exception was suppressed.", ScheduledReporter.this.getClass().getSimpleName(), ex);
}
}
}, period, period, unit);
}
```
This is a serious problem when the interval is sufficiently big. I suggest to add an alternative version of `ScheduledReporter.start()` to fix the bug without affecting code that relies on this behavior:
```
public void start(long period, long initialDelay, TimeUnit unit) {
executor.scheduleAtFixedRate(new Runnable() {
@Override
public void run() {
try { …
```
> ScheduledReporter.start() starts with undesired delay

- metrics-core/src/main/java/com/codahale/metrics/ScheduledReporter.java
With the current code exceptions that do not inherit from RuntimeException will
make this task die silently.
> Suppress all kinds of Exceptions raised by report()

- metrics-httpclient/src/test/java/io/dropwizard/metrics/httpclient/InstrumentedHttpClientsTest.java
Fixed test to catch `IOException` instead of just `NoHttpResponseException` since the test can throw a `SocketException: Connection reset` which would cause the test to fail
> metrics-httpclient test fix

- metrics-core/src/main/java/com/codahale/metrics/ExponentiallyDecayingReservoir.java
- metrics-core/src/main/java/com/codahale/metrics/ThreadLocalRandomProxy.java
- metrics-core/src/main/java/com/codahale/metrics/UniformReservoir.java
Add a factory which provides a ThreadLocalRandom implementation depending on its availability in runtime. If the JDK provides ThreadLocalRandom, use it. Otherwise, fallback to the internal implementation.
> Support the JDK's ThreadLocalRandom

- metrics-core/src/test/java/io/dropwizard/metrics/MetricNameTest.java
- pom.xml
Update maven-compiler-plugin to 3.6.1.
Add dependency on error-prone [1] and configure the compiler to use it.
Remove test statement that causes "[SelfEquals] An object is tested
for equality to itself" error [2].
[1] http://errorprone.info
[2] http://errorprone.info/bugpattern/SelfEquals
Change-Id: Id96a211e3013ca8913d3d7fd2eb1d7233890cd72
> Build with error-prone

- .travis.yml
- metrics-core/src/main/java/com/codahale/metrics/Counter.java
- metrics-core/src/main/java/com/codahale/metrics/EWMA.java
- metrics-core/src/main/java/com/codahale/metrics/Histogram.java
- metrics-core/src/main/java/com/codahale/metrics/LongAdderAdapter.java
- metrics-core/src/main/java/com/codahale/metrics/LongAdderProxy.java
- metrics-core/src/main/java/com/codahale/metrics/Meter.java
Add an ability to use the JDK's implementation if it's available in runtime. Add a factory for creating LongAdders which tries to use the JDK's implementation and fallbacks to the internal one if the JDK doesn't provide any. Unfortunately, LongAdders don't have a common interface, therefore we introduce `LongAdderAdapter`. It will be used in other components as an interface, a concrete implementation of it will be created by `LongAdderFactory`.
> Support JDK's LongAdder

- metrics-core/src/main/java/com/codahale/metrics/SlidingTimeWindowReservoir.java
- metrics-core/src/test/java/com/codahale/metrics/SlidingTimeWindowReservoirTest.java
The existing `trim` operation in `SlidingTimeWindowReservoir` assumes that values returned by `getTick` are strictly increasing.  When the result returned by `getTick` overflows, the `trim` operation will behave improperly - `trim` operations just after the overflow event will likely clear values within the current window, and `trim` operations well past the overflow event will likely fail to clear updates outside the current window (updates added before the overflow event).
To illustrate this behavior consider a reservoir with an 8-bit value returned by `getTick`, a window size of 2, and ignore the `trim` operations effect on the tick count:
```
update @123: 1
update @124: 2
update @125: 3
update @126: 4
update @127: 5
trim @127 - clears values before @125 (1, 2)
update @-128: 6
trim …
```
> Fix SlidingTimeWindowReservoir trim operation after overflow

- metrics-core/src/main/java/com/codahale/metrics/ExponentiallyDecayingReservoir.java
- metrics-core/src/test/java/com/codahale/metrics/ExponentiallyDecayingReservoirTest.java
Backport of #1033 to the 3.1.* branch.
> Backport rescale bug

- metrics-healthchecks/src/main/java/com/codahale/metrics/health/HealthCheckRegistry.java
- metrics-healthchecks/src/main/java/com/codahale/metrics/health/HealthCheckRegistryListener.java
- metrics-healthchecks/src/test/java/com/codahale/metrics/health/HealthCheckRegistryTest.java
A HealthCheckRegistryListener similarly to MetricRegistryListener which could be used to expose health checks elsewhere besides the admin page (like JMX).
Rebased version of #693
> Adding a HealthCheckRegistryListener

- metrics-core/src/main/java/com/codahale/metrics/MetricAttribute.java
- metrics-core/src/main/java/com/codahale/metrics/MetricType.java
- metrics-core/src/main/java/com/codahale/metrics/ScheduledReporter.java
- metrics-ganglia/src/main/java/com/codahale/metrics/ganglia/GangliaReporter.java
- metrics-ganglia/src/test/java/com/codahale/metrics/ganglia/GangliaReporterTest.java
- metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteReporter.java
- metrics-graphite/src/test/java/com/codahale/metrics/graphite/GraphiteReporterTest.java
This is for based on the work of @phauer in #1008. The set of disabled metrics is implemented in `ScheduledReporter`, so all reporters have an opportunity to implement this feature, but it's not necessarily (for instance `ConsoleReporter` doesn't really need it). Along with the Graphite reporter, the Ganglia reporter is also updated to support of disabling sending metrics.
> Support for disabled metrics

- metrics-jetty9/src/main/java/com/codahale/metrics/jetty9/InstrumentedHandler.java
- metrics-jetty9/src/test/java/com/codahale/metrics/jetty9/InstrumentedHandlerTest.java
Async requests are monitored via the addition of an async listener.
The bug was that `onStartAsync(AsyncEvent)` is called when the handler
invokes `startAsync()` but the `InstrumentedHandler` only added the
listener after the call to the delegate handler, thus would miss
the all onStartAsync event.
The net result of the bug was that the start time of all async requests
was reported as 0 so the calculated elapsed times where then rather
large (i.e. currentTimeMillis()).
> Fix for the monitoring jetty9 async servlet requests.

- metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteReporter.java
- metrics-graphite/src/test/java/com/codahale/metrics/graphite/GraphiteReporterTest.java
Currently, we trim all decimal values to 2 digits after the point. Despite that's a good default, some applications require reporting floating numbers with better precision.
For those users we provide the ability to override the `format(double v)` method of `GraphiteReporter`. User can provide a custom format (or just use a plain double-to-string conversion). We also need to make the constructor of `GraphiteReporter` protected, because users can't override a class with a private constructor.
> Add support for overriding format of floating numbers in Graphite

- metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteUDP.java
- metrics-graphite/src/test/java/com/codahale/metrics/graphite/GraphiteUDPTest.java
We can align `GraphiteUDP` with the TCP based `Graphite` and close the
socket in the `close` method instead of the connect method. The close
method will be invoked every time after a portion of metrics has been
sent, so we can close the socket there. We also do not need to call
the method `isConnected` during sending metrics because the socket is
opened right before sending data, so it can't be closed by timeout.
> Move closing` DatagramChannel` to the close method

- metrics-healthchecks/src/main/java/com/codahale/metrics/health/AsyncHealthCheckDecorator.java
- metrics-healthchecks/src/main/java/com/codahale/metrics/health/HealthCheck.java
- metrics-healthchecks/src/main/java/com/codahale/metrics/health/HealthCheckRegistry.java
- metrics-healthchecks/src/main/java/com/codahale/metrics/health/HealthCheckRegistryListener.java
- metrics-healthchecks/src/main/java/com/codahale/metrics/health/annotation/Async.java
- metrics-healthchecks/src/test/java/com/codahale/metrics/health/AsyncHealthCheckDecoratorTest.java
- metrics-healthchecks/src/test/java/com/codahale/metrics/health/HealthCheckRegistryTest.java
- metrics-healthchecks/src/test/java/com/codahale/metrics/health/HealthCheckTest.java
A backward compatible solution for asynchronous health checks (#609). HealthCheck implementations can be marked with the Async annotation while providing:
- execution period (mandatory)
- scheduling type (fixed rate or fixed delay)
- initial delay before first execution
- unit of period and delay
- initial health state until the first result is available
Async checks can be registered the same way regular health checks. On registration the health check registry is wrapping the async health check with a decorator that caches the last result and schedules a periodic execution. This decorator object is put into the underlying map and when its check is invoked it simply returns a cached result. On unregistration the registry cancels the task. To preserve the asynchronous behavior elsewhere …
> (#609) Introducing async health checks

- metrics-healthchecks/src/main/java/com/codahale/metrics/health/HealthCheckRegistry.java
- metrics-servlets/src/main/java/com/codahale/metrics/servlets/HealthCheckServlet.java
A follow-up for #1077 
* Add a method for graceful shutdown of HealthCheckRegistry
Add an ability to gracefully shutdown the executor for async tasks in `HealthCheckRegistry`.
Now it creates a ScheduledExecutorService which should be correctly closed when `HealthCheckRegistry` is not used anymore.
*  Make the pool size more pessimistic by default
Some CI environments return the amount of available processors as 128.
It's rather expensive to create such big thread pools by default. Let's start
with 2 threads and the user wants to increase the amount,  she can do that.
* Make the async health check threads as daemons
So they don't prevent the JVM from shutdown if the user didn't shut down
the executor gracefully.
> Shutdown health check registry

- docs/source/manual/third-party.rst
- Added new section for custom metrics implementations.
- Added link to rolling-metrics.
@marshallpierce, also I think that it would be better to move hdrhistogram-metrics-reservoir  to the new "Advansed metrics implementations" section because it is really provide new implementation of histogram and does not provide ability to monitor any library or server.
> Link to rolling-metrics library

- metrics-healthchecks/src/main/java/com/codahale/metrics/health/SharedHealthCheckRegistries.java
- metrics-healthchecks/src/test/java/com/codahale/metrics/health/SharedHealthCheckRegistriesTest.java
Add the ability to use a shared health check registry across different modules. The managed health check registry is set via the `setDefault` method and then it could be accessible by consumers via the `getDefault` method.
This is aligned with `SharedMetricRegistries`, which provides the same functionality.
> Add support for the default shared health check registry name

- metrics-core/src/main/java/com/codahale/metrics/SharedMetricRegistries.java
- metrics-core/src/test/java/com/codahale/metrics/SharedMetricRegistriesTest.java
Change `defaultRegistryName` from volatile to `AtomicReference`. This allows to us to perform an atomic set of the default registry bane and not end  up with a lost update.
This also adds a package-private setter for `defaultRegistryName` for testing purposes, so we don't perform any reflection hacks in the unit tests.
> Make SharedMetricRegistries thread-safe

- metrics-graphite/src/main/java/com/codahale/metrics/graphite/Graphite.java
- metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteRabbitMQ.java
- metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteSanitize.java
- metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteUDP.java
- metrics-graphite/src/main/java/com/codahale/metrics/graphite/PickledGraphite.java
- metrics-graphite/src/test/java/com/codahale/metrics/graphite/GraphiteSanitizeTest.java
As reported in #1098 the current sanitizer is too aggressive. It strips dots which play an important role in the Graphite metrics name convention. Until we develop a better algorithm, let's do only basic sanitization.
> Rollback GraphiteSanitize to replacing whitespaces

- metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteUDP.java
- metrics-graphite/src/test/java/com/codahale/metrics/graphite/GraphiteUDPTest.java
We can align `GraphiteUDP` with the TCP based `Graphite` and close the socket in the `close` method instead of the connect method. The close method will be invoked every time after a portion of metrics has been sent, so we can close the socket there. We also do not need to call the method `isConnected` during sending metrics because the socket is opened right before sending data, so it can't be closed by timeout.
Fixes #1100
> Move closing` DatagramChannel` to the close method (#1080)

- metrics-core/src/main/java/io/dropwizard/metrics/ConsoleReporter.java
- metrics-core/src/main/java/io/dropwizard/metrics/FixedNameCsvFileProvider.java
- metrics-core/src/main/java/io/dropwizard/metrics/MetricNameFormatter.java
- metrics-core/src/main/java/io/dropwizard/metrics/Slf4jReporter.java
- metrics-core/src/test/java/io/dropwizard/metrics/ConsoleReporterTest.java
- metrics-core/src/test/java/io/dropwizard/metrics/CsvReporterTest.java
- metrics-core/src/test/java/io/dropwizard/metrics/MetricNameFormatterTest.java
- metrics-core/src/test/java/io/dropwizard/metrics/Slf4jReporterTest.java
- metrics-graphite/src/main/java/io/dropwizard/metrics/graphite/GraphiteReporter.java
- metrics-graphite/src/test/java/io/dropwizard/metrics/graphite/GraphiteReporterTest.java
- pom.xml
This PR is an initial proposal on adding a `MetricNameFormatter`. The idea is users can provide an implementation that will format a `MetricName` into a string for reporters that only support single strings. This PR also makes the reporters aware of tags in the `MetricName`. Most of them currently just print out `MetricName.getKey()` which is not guaranteed to provide uniqueness for things such as the slf4j and console reporters. Let me know your thoughts
> Introduce a MetricNameFormatter 

- metrics-adapter/pom.xml
- metrics-jersey2/pom.xml
It looks like the groupId was changed to io.dropwizard.metrics4
but was missed in a few places.
> Fix groupId in pom.xml files

- metrics-adapter/pom.xml
- metrics-benchmarks/pom.xml
- metrics-collectd/pom.xml
- metrics-ehcache/pom.xml
- metrics-graphite/pom.xml
- metrics-healthchecks/pom.xml
- metrics-httpasyncclient/pom.xml
- metrics-httpclient/pom.xml
- metrics-influxdb/pom.xml
- metrics-jdbi/pom.xml
- metrics-jersey2/pom.xml
- metrics-jetty9/pom.xml
- metrics-json/pom.xml
- metrics-jvm/pom.xml
- metrics-log4j2/pom.xml
- metrics-logback/pom.xml
- metrics-servlet/pom.xml
- metrics-servlets/pom.xml
It was already done like that for some; do it for all, to make it
consistent.
> Use ${project.groupId} in child pom.xml dependency declarations

- metrics-core/src/main/java/com/codahale/metrics/UniformSnapshot.java
- metrics-core/src/test/java/com/codahale/metrics/UniformSnapshotTest.java
The current code for creating a snapshot from the collection is unfortunately broken. The code fails if the provided collection is modified during creating of the snapshot and it has a weak iterator (precisely what `ConcurrentSkipListMap` provides). The iterator doesn't guarantee that it has exactly the same amount iteration as the size of the collection. As a result, the code throws an `ArrayIndexOutOfBoundException`.
The correct behaviour is too dump the collection to a resizable array on the fly and then convert it the array of long primitives.
The behaviour was correct in the 3.1 branch, but was broken in 3.2 by the optimization in #972.
Fixes #1104
> Fix creating a uniform snapshot from a collection

- metrics-adapter/src/main/java/com/codahale/metrics/health/HealthCheck.java
- metrics-core/src/test/java/io/dropwizard/metrics/InstrumentedExecutorServiceTest.java
- metrics-core/src/test/java/io/dropwizard/metrics/InstrumentedScheduledExecutorServiceTest.java
- metrics-jvm/src/test/java/io/dropwizard/metrics/jvm/FileDescriptorRatioGaugeTest.java
- metrics-servlet/src/main/java/io/dropwizard/metrics/servlet/AbstractInstrumentedFilter.java
Methods that override the implementation from a superclass or
interface should be annotated with @Override as described in:
http://stackoverflow.com/a/94411/381622
> Add missing @Override annotations

- metrics-core/src/main/java/com/codahale/metrics/ScheduledReporter.java
- metrics-core/src/test/java/com/codahale/metrics/ScheduledReporterTest.java
Hello! This was something I noticed while testing metric conversions recently.
For a precision test like this:
```java
@Test
public void shouldConvertDurationToMillisecondsPrecisely() {
assertEquals(2.0E-5, reporter.convertDuration(20), 0.0);
}
```
The current implementation will fail:
```
java.lang.AssertionError: 
Expected :2.0E-5
Actual   :1.9999999999999998E-5
```
However, if we perform the division directly on given durations, the test will pass.
I don't believe this change degrades the precision for other inputs, but happy to hear otherwise and backpedal :)
> Improve ScheduledReporter convertDurations precision

- metrics-httpasyncclient/src/main/java/io/dropwizard/metrics/httpasyncclient/InstrumentedNHttpClientBuilder.java
- metrics-httpasyncclient/src/test/java/io/dropwizard/metrics/httpasyncclient/HttpClientTestBase.java
- metrics-httpasyncclient/src/test/java/io/dropwizard/metrics/httpasyncclient/InstrumentedHttpClientsTest.java
- metrics-httpasyncclient/src/test/java/io/dropwizard/metrics/httpasyncclient/InstrumentedHttpClientsTimerTest.java
This PR fixes a problem with the httpasyncclient metrics integration. 
The previous approach did not actually time the request execution but the time to return the `Future` of the response. This was discovered when introducing latency in our code that wasn't reflected at all in the metrics we gathered from the async client library.
Changes:
- The first commit is the minimal change, it does slightly tweak the existing test (using Mockito annotations) as part of introducing another test suite for the timing tests.
- The second commit replaces the `AssertionError` that is being thrown with a `RuntimeException` (this code should not throw an `Error`).
- The last commit refactors and enhances the tests to use a local server instead of making requests to `example.com`.
Happy to change the scope …
> Fix metrics httpasyncclient timing master

- metrics-core/src/main/java/com/codahale/metrics/LongAdderProxy.java
- metrics-core/src/main/java/com/codahale/metrics/ThreadLocalRandomProxy.java
We should try to load an actual value of a `ThreadLocal`, because in some environments (like WebLogic) a `NoClassDefException` won't be thrown during loading of `JdkProvider`.
We should also catch all possible errors, not only `NoClassDefException` to avoid a situation when the provider becomes a null reference.
Originally reported in #1129
> Make checks for existence of ThreadLocal more robust

- metrics-core/src/main/java/com/codahale/metrics/ExponentiallyDecayingReservoir.java
- metrics-core/src/main/java/com/codahale/metrics/WeightedSnapshot.java
- metrics-core/src/test/java/com/codahale/metrics/ExponentiallyDecayingReservoirTest.java
Exponentially Decaying Reservoir was giving incorrect values in the snapshot if the inactive period was too long. This could result in wrong metrics aggregation.
> Exponentially decaying reservoir update

- metrics-healthchecks/src/main/java/com/codahale/metrics/health/HealthCheck.java
- metrics-healthchecks/src/test/java/com/codahale/metrics/health/HealthCheckTest.java
Use String.valueOf in toString of HealthCheck.Result to avoid NullPointerException when it has a detail with null value.
Prepend ", " to any details, to make the resulting String more readable.
> Avoid npe in toString of HealthCheck.Result

- docs/source/manual/core.rst
- metrics-core/src/main/java/com/codahale/metrics/ChunkedAssociativeLongArray.java
This change makes `ChunkedAssociativeLongArray` traversable from both sides (from tail and
from head). This actually simplifies the code and give us ability to optimize `ChunkedAssociativeLongArray.trim()` logic, what I actually did :smile:.
So now `SlidingTimeWindowArrayReservoir` speed is back and now it is even faster:
In ReservoirBenchmark: updates are **5.5x** faster and **~100x** less time spent in GC than `SlidingTimeWindowReservoir`
In SlidingTimeWindowReservoirsBenchmark: updates are **3.4x** faster, reads - **2.6x** faster, **35x** less time spent in GC.
With this changes `SlidingTimeWindowArrayReservoir` is actually comparable with `ExponentiallyDecayingReservoir` in terms of performance and now the only concern is memory overhead which is **~128** bits per stored measurement.
> ChunkedAssociativeLongArray traversable from both sides

- metrics-core/src/main/java/com/codahale/metrics/ChunkedAssociativeLongArray.java
This change gives `ChunkedAssociativeLongArray` ability to store chunks that are expired and removed from main data structure.
Then instead of allocating new Chunk immediately we are trying to poll one from this cache.
So if you have constant or slowly changing load ChunkedAssociativeLongArray will never throw away old chunks or allocate new ones which makes this data structure almost garbage free. Also chunks stored in cache as `SoftReference`s so this memory can actually be freed if nesesary.
---
Numbers:
In `ReservoirBenchmark`: updates are **5.9x** faster and **~370x** less time spent in GC than `SlidingTimeWindowReservoir`.
In `SlidingTimeWindowReservoirsBenchmark`: updates are **3.2x** faster, reads - **2.7x** faster, **37x** less time spent in GC. (here we see small difference …
> ChunkedAssociativeLongArray re-use expired nodes

- metrics-healthchecks/src/main/java/com/codahale/metrics/health/SharedHealthCheckRegistries.java
Currently, there exists only one method for getting the default health
check registry - `getDefault`. Unfortunately, it throws an
`IllegalStateException` if the registry is not set. End users need to
check for this condition. Some users would like avoid using
exceptions for the control flow and would prefer to make a null check
instead catching an exception. For them we provide the `tryGetDefault`
method which does exactly that.
> Add ability to get default health check registry without an exception

- metrics-adapter/pom.xml
- pom.xml
Updates the findbugs plugin to the latest version and fixes the minimum maven version to prevent an error reported by the versions checker.
> Update findbugs plugin to latest version

- metrics-jersey2/src/main/java/com/codahale/metrics/jersey2/InstrumentedResourceMethodApplicationListener.java
- metrics-jersey2/src/main/java/com/codahale/metrics/jersey2/MetricsFeature.java
- metrics-jersey2/src/test/java/com/codahale/metrics/jersey2/SingletonMetricsJerseyTest.java
- metrics-jersey2/src/test/java/com/codahale/metrics/jersey2/TestClock.java
- metrics-jersey2/src/test/java/com/codahale/metrics/jersey2/resources/InstrumentedResource.java
- metrics-jersey2/src/test/java/com/codahale/metrics/jersey2/resources/InstrumentedSubResource.java
- metrics-jersey2/src/test/java/com/codahale/metrics/jersey2/resources/TestRequestFilter.java
This adds support for measuring time for the entire request processing, and the request and response filtering steps, in addition to the current measurement of the time used by the request method itself. In addition, support is added for letting users specify the clock to be used.
No extra metrics are added for methods with @Timed annotations that specify an explicit name, as it's not really clear what those extra metrics should be named, and it seems wrong to add attributes to the @Timed annotation for jersey-specific concepts. Ideas for how to add the extra metrics for explicitly named methods welcome!
Corresponding PR for master: #1119
> Feature/filter metrics v3.2
